### ISSUE TITLE
follow preloaded_json guide nowdays

### ISSUE THREAD

**Issue by jomin398** [pixijs/spine#479]
following guide on [here](https://github.com/pixijs/spine/blob/master/examples/preloaded_json.md) nowdays..  
used umd https://cdn.jsdelivr.net/npm/pixi-spine@3.1.2/dist/pixi-spine.umd.js
``` js
//with spine umd. 
//this one is loaded fine...
var rawSkelJson = ""; //loaded fine with fetch...
var spineAtlas = new PIXI.spine.TextureAtlas(rawAtlasData, function(line, callback) {
        // pass the image here.
        // console.log(line)
        callback(PIXI.BaseTexture.from(textureLst[line]));
    });

var spineAtlasLoader = new PIXI.spine.core.AtlasAttachmentLoader(spineAtlas)
var spineJsonParser = new PIXI.spine.core.SkeletonJson(spineAtlasLoader);
var spineData = spineJsonParser.readSkeletonData(rawSkelJson);
```

where is `AtlasAttachmentLoader`?

**Comment by ivanpopelyshev** [comment]
Its different depending on runtime. If  you use pixi-spine , you dont have actual access to it. Use umd from `@pixi-spine/all-4.1` to get access to those things.

**Comment by jomin398** [comment]
I cant use `all/4.1` on front-only(like github page) browser.
I can only use via cdn.

Possibility to use it with `importmap`
I don't know how use it..

**Comment by ivanpopelyshev** [comment]
Sorry, I cant help you with that. People requested us to support ALL versions of spine, which no other official runtime does - we added it, and it that costs something. Build tools are more difficult, and there are a number of packages. 

Please provide minimal demo with `all/4.1` that doesnt work for you.

**Comment by jomin398** [comment]
# And how to fix This happen?
>Uncaught (in promise) TypeError: First argument to DataView constructor must be an ArrayBuffer  
    at new DataView (<anonymous>)
    at new BinaryInput2 (base.js:28:16)
    at SkeletonBinary2.readSkeletonData (runtime-4.1.js:5654:17)
    at pixiTest.js:38:27

```js
import * as PIXI from 'https://cdn.skypack.dev/pixijs@7.x';
// import { Loader } from 'https://cdn.skypack.dev/@pixi/loaders';
import * as PSpine from 'https://cdn.skypack.dev/@pixi-spine/all-4.1';
import { PixiStatsPlugin } from 'https://cdn.skypack.dev/@armathai/pixi-stats';
//for debug.
// window.PIXI = PIXI;
// window.PSpine = PSpine; 
let gUrls = []; // leave for remove created ObjectURLs later.
const assets = await (async () => {
    let assets = [];
    //Lefted STRING after checking the .atlas file
    assets.push((await fetch('./asset/c112_00.atlas')).text());
    //Temporarily apply Dataurl from de-compressed with jszip.
    await (async (a) => {

        let u = URL.createObjectURL(new Blob([await (await fetch('./asset/c112_00.png')).arrayBuffer()], { type: "image/png" }));
        a.push(u);
        assets.push({ 'c112_00.png': u })
    })(gUrls)
    //Temporarily apply Dataurl from de-compressed with jszip.
    await (async (a) => {
        let u = URL.createObjectURL(new Blob([await (await fetch('./asset/c112_00.skel')).arrayBuffer()], { type: "application/octet-stream" }));
        a.push(u);
        assets.push(u)
    })(gUrls)
    assets.push(await (await fetch('./asset/c112_00.skel')).arrayBuffer());
    return await Promise.all(assets);
})();
var app = new PIXI.Application();
app.stage.interactive = true;
document.body.appendChild(app.view);
(async () => {
    let spineAtlas = new PSpine.TextureAtlas(assets[0], async function (line, callback) {
        callback(PIXI.BaseTexture.from(assets[1][line]))
    });
    let spineAtlasLoader = new PSpine.AtlasAttachmentLoader(spineAtlas);
    let paser = new PSpine.SkeletonBinary(spineAtlasLoader);

    //thrown error here, as TypeError: First argument to DataView constructor must be an ArrayBuffer
    let spineData = paser.readSkeletonData(await (await fetch(assets[2])).arrayBuffer())
    console.log(spineData)
})();
```
