### ISSUE TITLE
I had trouble playing Spine animations

### ISSUE THREAD

**Issue by Squirrel39401** [pixijs/spine#494]
version:3.8
spineFileVersion:3.6.38
error:Uncaught RangeError: Offset is outside the bounds of the DataView
    at DataView.getUint8 (<anonymous>)
    at BinaryInput.readUnsignedByte (pixi-spine.js:52:32)
    at BinaryInput.readString (pixi-spine.js:100:30)
    at SkeletonBinary.readAttachment (pixi-spine.js:8363:30)
    at SkeletonBinary.readSkin (pixi-spine.js:8354:43)
    at SkeletonBinary.readSkeletonData (pixi-spine.js:8113:36)
    at SpineParser.parseData (pixi-spine.js:9978:45)
    at pixi-spine.js:2637:38
    at iterateParser (pixi-spine.js:581:44)
    at pixi-spine.js:619:29
[dynamic.zip](https://github.com/pixijs/spine/files/11078798/dynamic.zip)

**Comment by nemyagky** [comment]
Same. Did you managed to solve it?
